version: '3.8'
services:
  db: 
    image: mysql:latest
    container_name: mysql_c
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: nest_js_db
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-password
    ports:
      - "3306:3306"