version: '3.9'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  app:
    container_name: app
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork: